# Generated by Django 5.2.8 on 2026-01-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Economic_Region_Employment_Estimate',
            fields=[
                ('datestamp', models.TextField(blank=True, null=True)),
                ('dguid', models.TextField(blank=True, db_column='DGUID', null=True)),
                ('noc_groupingid', models.IntegerField(blank=True, db_column='NOC_GroupingID', null=True)),
                ('employment_estimate_3_month_moving_average', models.FloatField(blank=True, db_column='Employment Estimate 3 Month Moving Average', null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('month', models.IntegerField(blank=True, db_column='Month', null=True)),
                ('employment_pct_change', models.FloatField(blank=True, db_column='Employment PCT Change', null=True)),
                ('entryid', models.IntegerField(db_column='EntryID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Tbl_Economic_Region_NOC_Employment_Estimate_TS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Economic_Region_Vacancy_Wage_Estimate',
            fields=[
                ('datestamp', models.TextField(blank=True, null=True)),
                ('dguid', models.TextField(blank=True, db_column='DGUID', null=True)),
                ('noc_code', models.TextField(blank=True, db_column='NOC Code', null=True)),
                ('average_offered_hourly_wage', models.FloatField(blank=True, db_column='Average offered hourly wage', null=True)),
                ('job_vacancies', models.FloatField(blank=True, db_column='Job vacancies', null=True)),
                ('classid', models.IntegerField(blank=True, db_column='ClassID', null=True)),
                ('entryid', models.IntegerField(db_column='EntryID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Tbl_Economic_Region_NOC_Vacancy_And_Wage_Estimate_TS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EconomicRegion',
            fields=[
                ('economicregionid', models.IntegerField(db_column='EconomicRegionID', primary_key=True, serialize=False)),
                ('economicregion_dguid', models.TextField(blank=True, db_column='EconomicRegion_DGUID', null=True)),
                ('economicregion', models.TextField(blank=True, db_column='EconomicRegion', null=True)),
                ('provinceid', models.IntegerField(blank=True, db_column='ProvinceID', null=True)),
                ('province_dguid', models.TextField(blank=True, db_column='Province_DGUID', null=True)),
            ],
            options={
                'db_table': 'Tbl_Economic_Regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NOC_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelid', models.IntegerField(blank=True, db_column='LevelID', null=True)),
                ('levelname', models.TextField(blank=True, db_column='LevelName', null=True)),
            ],
            options={
                'db_table': 'Tbl_NOC_Levels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NOCClass',
            fields=[
                ('classid', models.IntegerField(db_column='ClassID', primary_key=True, serialize=False)),
                ('levelid', models.IntegerField(blank=True, db_column='LevelID', null=True)),
                ('noc_code', models.IntegerField(blank=True, db_column='NOC Code', null=True)),
                ('noc_class', models.TextField(blank=True, db_column='NOC Class', null=True)),
                ('class_definition', models.TextField(blank=True, db_column='Class Definition', null=True)),
            ],
            options={
                'db_table': 'Tbl_Occupations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NOCGrouping',
            fields=[
                ('noc_groupingid', models.IntegerField(db_column='NOC_GroupingID', primary_key=True, serialize=False)),
                ('noc_grouping', models.TextField(blank=True, db_column='NOC_Grouping', null=True)),
                ('unnamed_2', models.FloatField(blank=True, db_column='Unnamed: 2', null=True)),
            ],
            options={
                'db_table': 'Tbl_NOC_TS_Groupings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Program_NOC_Link',
            fields=[
                ('linkid', models.IntegerField(db_column='LinkID', primary_key=True, serialize=False)),
                ('programid', models.IntegerField(blank=True, db_column='ProgramID', null=True)),
                ('program', models.TextField(blank=True, db_column='Program', null=True)),
                ('broad_occupation_category_code', models.IntegerField(blank=True, db_column='Broad Occupation Category Code', null=True)),
                ('broad_occupation_category', models.TextField(blank=True, db_column='Broad Occupation Category', null=True)),
                ('major_group_code', models.IntegerField(blank=True, db_column='Major Group Code', null=True)),
                ('major_group', models.TextField(blank=True, db_column='Major Group', null=True)),
                ('sub_major_group_code', models.IntegerField(blank=True, db_column='Sub-Major Group Code', null=True)),
                ('sub_major_group', models.TextField(blank=True, db_column='Sub-Major Group', null=True)),
                ('minor_group_code', models.IntegerField(blank=True, db_column='Minor Group Code', null=True)),
                ('minor_group', models.TextField(blank=True, db_column='Minor Group', null=True)),
                ('unit_group_code', models.IntegerField(blank=True, db_column='Unit Group Code', null=True)),
                ('unit_group_occupation', models.TextField(blank=True, db_column='Unit Group Occupation', null=True)),
                ('unit_group_description', models.TextField(blank=True, db_column='Unit Group Description', null=True)),
            ],
            options={
                'db_table': 'Tbl_ProgramOccupations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Program_University_KPI',
            fields=[
                ('entryid', models.IntegerField(db_column='EntryID', primary_key=True, serialize=False)),
                ('universityid', models.IntegerField(blank=True, db_column='UniversityID', null=True)),
                ('university', models.TextField(blank=True, db_column='University', null=True)),
                ('programcategoryid', models.IntegerField(blank=True, db_column='ProgramCategoryID', null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('employment_rate_2_years_after_graduating_field', models.TextField(blank=True, db_column='Employment Rate (2 years after graduating)', null=True)),
                ('employment_rate_6_months_after_graduating_field', models.TextField(blank=True, db_column='Employment Rate (6 months after graduating)', null=True)),
                ('graduation_rate', models.TextField(blank=True, db_column='Graduation Rate', null=True)),
            ],
            options={
                'db_table': 'Tbl_ProgramUniversityKPI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('programcategoryid', models.IntegerField(db_column='ProgramCategoryID', primary_key=True, serialize=False)),
                ('programcategory', models.TextField(blank=True, db_column='ProgramCategory', null=True)),
            ],
            options={
                'db_table': 'Tbl_ProgramCategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('provinceid', models.IntegerField(db_column='ProvinceID', primary_key=True, serialize=False)),
                ('province_dguid', models.TextField(blank=True, db_column='Province_DGUID', null=True)),
                ('province', models.TextField(blank=True, db_column='Province', null=True)),
                ('province_shorthand', models.TextField(blank=True, db_column='Province_Shorthand', null=True)),
            ],
            options={
                'db_table': 'Tbl_Provinces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincial_NOC_Group_Labor_Statistic',
            fields=[
                ('datestamp', models.TextField(blank=True, null=True)),
                ('noc_groupingid', models.IntegerField(blank=True, db_column='NOC_GroupingID', null=True)),
                ('noc_grouping', models.TextField(blank=True, db_column='NOC_Grouping', null=True)),
                ('dguid', models.TextField(blank=True, db_column='DGUID', null=True)),
                ('labour_force', models.FloatField(blank=True, db_column='Labour force', null=True)),
                ('employment', models.FloatField(blank=True, db_column='Employment', null=True)),
                ('part_time_employment', models.FloatField(blank=True, db_column='Part-time employment', null=True)),
                ('full_time_employment', models.FloatField(blank=True, db_column='Full-time employment', null=True)),
                ('unemployment', models.FloatField(blank=True, db_column='Unemployment', null=True)),
                ('unemployment_rate', models.FloatField(blank=True, db_column='Unemployment rate', null=True)),
                ('employment_moving_average', models.FloatField(blank=True, db_column='Employment Moving Average', null=True)),
                ('employment_moving_sd', models.FloatField(blank=True, db_column='Employment Moving SD', null=True)),
                ('employment_upper_band', models.FloatField(blank=True, db_column='Employment Upper Band', null=True)),
                ('employment_lower_band', models.FloatField(blank=True, db_column='Employment Lower Band', null=True)),
                ('entryid', models.IntegerField(db_column='EntryID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Tbl_Provincial_NOC_Labor_Statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('universityid', models.IntegerField(db_column='UniversityID', primary_key=True, serialize=False)),
                ('university', models.TextField(blank=True, db_column='University', null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('province', models.TextField(blank=True, db_column='Province', null=True)),
                ('city', models.TextField(blank=True, db_column='City', null=True)),
                ('postalcode', models.TextField(blank=True, db_column='PostalCode', null=True)),
                ('lat', models.FloatField(blank=True, db_column='Lat', null=True)),
                ('lon', models.FloatField(blank=True, db_column='Lon', null=True)),
            ],
            options={
                'db_table': 'Tbl_Universities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PredictionCache',
            fields=[
                ('entryid', models.IntegerField(db_column='EntryID', primary_key=True, serialize=False)),
                ('datestamp', models.TextField(blank=True, db_column='ds', null=True)),
                ('provinceid', models.IntegerField(blank=True, db_column='ProvinceID', null=True)),
                ('dguid', models.TextField(blank=True, db_column='dguid', null=True)),
                ('noc_groupingid', models.IntegerField(blank=True, db_column='noc_groupingid', null=True)),
                ('y', models.FloatField(blank=True, db_column='y', null=True)),
                ('yhat_lower', models.FloatField(blank=True, db_column='yhat_lower', null=True)),
                ('yhat', models.FloatField(blank=True, db_column='yhat', null=True)),
                ('yhat_upper', models.FloatField(blank=True, db_column='yhat_upper', null=True)),
                ('set', models.TextField(blank=True, db_column='Set', null=True)),
            ],
            options={
                'db_table': 'Tbl_Temp_Forecasts',
            },
        ),
    ]
